[package]
name = "fhe-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.7.3", features = [ "boolean", "shortint", "integer", "aarch64-unix" ] }
rayon = "1.7"
lazy_static = "1.4"
